Numpy Random Module
* rand: Random Values in a given Shape
* randn: Return a sample from the "standard normal" distribution
* randint: Return random integers from low(inclusive) to high(exclusive)
* random: Return random floats in the half-open interval[0.0, 1,)
* choice: Generates a random sample from a given 1d array
* shuffle: Suffles the contents of a sequence

In [3]:
import numpy as np

In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
a=np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
np.random.shuffle(a) #shuffles array in random order
print(a)

[13 10  5 12 11  8 14  7  9  6]


In [11]:
# generate array of random nos
#returns values from a standard normal distribution
a=np.random.rand(2,3)
print(a)

a=np.random.randint(5,10,3) #
print(a)

[[0.49102526 0.35059813 0.80538337]
 [0.37499737 0.87393155 0.30933799]]
[5 8 7]


In [13]:
#randomly pick one element from an array

element=np.random.choice([1,4,3,2])
print(element)

3


In [ ]:
#if we want our random nos to be generated in the same order, we have to set a seed
a=np.arange(10)
np.random.seed(1)
print(a)