Working with Numpy- for mathematical operations

In [1]:
import numpy as np

In [2]:
#creating an array in numpy
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#The concept of shapes
#(5,)means that the array is linear [1d matrix]
print(arr.shape)

(5,)


In [9]:
brr=np.array([[1],[2],[3],[4],[5]])
print(brr)
print(brr.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [10]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])#accessing elements

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [11]:
#Create Zeros, Ones, Custom array
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#Array of constants
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [15]:
#Identity Matrix-Size/Square Matrix
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#Random Matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0.11662446 0.88918496 0.04656957]
 [0.65044089 0.89061847 0.76252057]]


In [20]:
print(randomMatrix[:,1])#[row,col] : means all

[0.88918496 0.89061847]


In [22]:
randomMatrix[1,1:3]=1#Slicing
print(randomMatrix)

[[0.11662446 0.88918496 0.04656957]
 [0.65044089 1.         1.        ]]


In [23]:
##Set rows and columns with any values
z=np.zeros((3,3))
print(z)
z[1,:]=5
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [24]:
z[:,-1]=7
print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [26]:
#datatypes
print(z.dtype)

float64


In [28]:
#to convert to int
z=np.zeros((3,3), dtype=np.int64)

In [29]:
print(z.dtype)

int64


In [30]:
#Mathematical Operations

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
#element wise add
print(x+y)


[[ 6  8]
 [10 12]]


In [31]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [32]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [33]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [34]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [36]:
#Matrix Multiplication/Dot Products
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [37]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [38]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [39]:
#Multiplication of vectors
#Multiplication of vectors-scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [40]:
print(a)

[1 2 3 4]


In [41]:
print(sum(a))

10


In [42]:
print(x)

[[1 2]
 [3 4]]


In [43]:
print(np.sum(x))

10


In [44]:
print(np.sum(x,axis=0))#sum along the column

[4 6]


In [45]:
print(np.sum(x,axis=1))

[3 7]


In [46]:
#Stacking of arrays
b=b*2
print(a)
print(b)


[1 2 3 4]
[2 4 6 8]


In [47]:
np.stack((a,b),axis=1)

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [48]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [49]:
#reshape a numpy array
a=np.stack((a,b),axis=0)
print(np.shape(a))

(2, 4)


In [53]:
a=a.reshape((4,2))
print(a)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]
