Statistical Computation Using Numpy
* min,max
* mean
* median
* average
* variance
* standard deviation

In [2]:
import numpy as np
a= np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [3]:
print(np.min(a)) #min in the entire array

0


In [6]:
# min along each axis
print(np.min(a,axis=0)) # along each column
print(np.min(a,axis=1))# along each row

[1 2 2 0]
[1 0]


In [8]:
#Mean, average of all elements
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)

print(np.mean(b))

3.0
3.0


In [10]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[4.  4.  2.5 2. ]
[2.5  3.75]


In [11]:
#Median
c=np.array([1,5,2,4,0])
print(np.median(c))

2.0


In [12]:
#Standard Deviation-Standard deviation is the square root of the average of square deviations from mean
a = np.array([5,6,7]) 
print(a)
print(np.std(a))

[5 6 7]
0.816496580927726


In [13]:
#Variance-Variance is the average of the square deviations.
a = np.array([5,6,7]) 
print(a)
print(np.var(a))

[5 6 7]
0.6666666666666666


NumPy Average Function
NumPy np.average() function determines the weighted average along with the multi-dimensional arrays. The weighted average is calculated by multiplying the component by its weight, the weights are specified separately. If weights are not specified it produces the same output as mean.

In [14]:
#Average
a = np.array([5,6,7]) 
print(a)
#without weight same as mean
print(np.average(a))
#with weight gives weighted average
wt = np.array([8,2,3])
print(np.average(a, weights=wt))

[5 6 7]
6.0
5.615384615384615


In [16]:
#NumPy Percentile Function
a = np.array([2,10,20])  
print(a)  
print(np.percentile(a,10,0))

[ 2 10 20]
3.6


In [17]:
#NumPy Peak-to-Peak Function
#useful to determine the range of values along an axis.
a = np.array([[2,10,20],[6,10,60]])  
print(np.ptp(a,0))

[ 4  0 40]
